name: 'Run Frontend Tests'
description: 'Run unit tests for frontend with coverage'

inputs:
  working-directory:
    description: 'Working directory for the frontend'
    required: true
    default: 'Client'
  coverage-path:
    description: 'Path to store coverage results'
    required: true
    default: 'coverage'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '${{ inputs.working-directory }}/.nvmrc'
        cache: 'npm'
      working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Run tests with coverage
      run: npm run test:coverage
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        directory: ${{ inputs.working-directory }}/${{ inputs.coverage-path }}
        fail_ci_if_error: false
